# Basic stuff not available on Nix
brew "m-cli"

# install fonts
tap "homebrew/cask-fonts"
cask "font-jetbrains-mono-nerd-font"
cask "font-fira-code"
cask "font-fira-code-nerd-font"

mas "Windows App", id: 1295203466
